---
title: "testowanie ml"
author: "Tomasz Chudziak"
date: "21 11 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#https://towardsdatascience.com/create-predictive-models-in-r-with-caret-12baf9941236
```

ML
```{r}
library(C50)
library(caret)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(lattice)
library(plotly)
library(lubridate)
library(tibble)
library(rmarkdown)

setwd("D:\\studia\\ZED\\projekt\\Data pack\\")
goldPrice <- read.csv(file = "Gold prices.csv")
currencyExchangeRates <-  read.csv(file = "CurrencyExchangeRates.csv")
spComposite <-  read.csv(file = "S&P Composite.csv")
#worldDevelopmentIndicators <- read_excel("World_Development_Indicators.xlsx")

```

```{r}
gp<- goldPrice %>% 
    mutate(Date=as.Date(Date,format="%Y-%m-%d")) %>% 
    mutate(usd=
        ifelse(is.na(USD..AM.), USD..PM.,
            ifelse(is.na(USD..PM.), USD..AM.,
                round((USD..AM.+USD..PM.)/2.0,digits=2)
            )
        ),
        gbp=
        ifelse(is.na(GBP..AM.), GBP..PM.,
            ifelse(is.na(GBP..PM.), GBP..AM.,
                round((GBP..AM.+GBP..PM.)/2.0,digits=2)
            )
        ),
        euro=
        ifelse(is.na(EURO..AM.), EURO..PM.,
            ifelse(is.na(EURO..PM.), EURO..AM.,
                round((EURO..AM.+EURO..PM.)/2.0,digits=2)
            )
        )
    ) %>% 
    rename(g_date=Date, g_usd=usd, g_gbp=gbp,g_euro=euro) %>%
    select(g_date,g_usd,g_gbp,g_euro)

spComposite <- spComposite %>%
  mutate(Year=as.Date(Year,format="%Y-%m-%d"))

```

```{r ml_ceny_zlota_a_akcje_spolki}
df1 <- gp%>%rename(Year=g_date)

df3<-df1%>%
  inner_join(spComposite) %>%
  select(g_usd, Dividend,Earnings,CPI,Real.Dividend,S.P.Composite,Real.Earnings,Real.Price)%>%
  drop_na
  

head(df3)
set.seed(23)

inTraining <- 
    createDataPartition(
        y = df3$g_usd,
        p = .75,
        list = FALSE)

training <- df3[ inTraining,]
testing  <- df3[-inTraining,]


model <- train(g_usd ~ .,
               data = training,
               method = "lm")
model
predictions <- predict(model, testing)

RMSE(predictions, testing$g_usd)
postResample(pred = predictions, obs = testing$g_usd)


model <- train(g_usd ~ .,
               data = training,
               method = "ridge")
model
predictions <- predict(model, testing)

RMSE(predictions, testing$g_usd)
postResample(pred = predictions, obs = testing$g_usd)


model <- train(g_usd ~ .,
               data = training,
               method = "lasso")
model
predictions <- predict(model, testing)

RMSE(predictions, testing$g_usd)
postResample(pred = predictions, obs = testing$g_usd)


fitControl <- trainControl(method = "repeatedcv",   
                           number = 10,     # number of folds
                           repeats = 10)    # repeated ten times


model.cv <- train(g_usd ~ .,
               data = training,
               method = "lm",  # now we're using the lasso method
               trControl = fitControl)  

model
predictions <- predict(model, testing)

RMSE(predictions, testing$g_usd)
postResample(pred = predictions, obs = testing$g_usd)


tmp<- testing
tmp$pred<-predictions
tmp<-tmp%>%select(g_usd,pred)
head(tmp)
```


```{r}
# data(churn)
# summary(churnTrain)
# head(churnTrain)
# set.seed(23)
# 
# 
# ctrl <- trainControl(
#     # powtórzona ocena krzyżowa
#     method = "repeatedcv",
#     # liczba podziałów
#     number = 2,
#     # liczba powtórzeń
#     repeats = 5)
# 
# fit <- train(churn ~ .,
#              data = churnTrain,
#              method = "rf",
#              trControl = ctrl,
#              # Paramter dla algorytmu uczącego
#              ntree = 10)
#  
# rfClasses <- predict(fit, newdata = churnTest)
# confusionMatrix(data = rfClasses, churnTest$churn)
```